# when running hexo in a subdirectory (e.g. domain.tld/blog), remove leading slashes ( "/archives" -> "archives" )

version: 2.0
# Place your favicon.ico to /source directory.
favicon: /favicon.ico

# Set default keywords (Use a comma to separate)
keywords: "Android"

debug: false

menu:
<<<<<<< HEAD
  简书: http://www.jianshu.com/users/01e73279ab1a/latest_articles
=======
>>>>>>> 8a652121e27bfe3a1f09d0a6ffb6a8eca0b4e361
  GitHub: https:github.com/wujingchao

plugins: 
	- hexo-generator-sitemap
	- hexo-generator-feed
<<<<<<< HEAD
=======


>>>>>>> 8a652121e27bfe3a1f09d0a6ffb6a8eca0b4e361
